export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Anton Belousov",
  jobTitle: "Middle Frontend Developer",
  email: "polpoltrop228@gmail.com",
  telephone: "+380663208556",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Kyiv",
    addressCountry: "Ukraine",
  },
  url: "https://github.com/AntonBelousovWEB",
  sameAs: [
    "https://github.com/AntonBelousovWEB",
    "https://www.linkedin.com/in/anton-belousov-1803042b1/",
    "/blog",
  ],
  description:
    "Frontend developer with experience since 2020, specializing in creating high-performance and SEO-optimized web applications.",
  hasOccupation: {
    "@type": "Occupation",
    name: "Frontend Developer",
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Redux",
      "GraphQL",
      "Tailwind CSS",
      "SEO Optimization",
      "Performance Tuning",
      "Apollo Client",
      "React Query",
      "TanStack Query",
      "Material UI",
      "Ant Design",
      "Webpack",
      "Vite",
      "Babel",
      "ESLint",
      "Prettier",
      "Git",
      "GitHub",
      "GitLab",
      "Figma",
      "Postman",
      "Jest",
      "React Testing Library",
      "Lighthouse",
      "Google PageSpeed Insights",
      "Schema.org",
      "WhatWG",
    ],
    responsibilities:
      "Development of high-performance web applications, technical SEO optimization, code refactoring and performance improvements.",
  },
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Kyiv",
      addressCountry: "Ukraine",
    },
  },
  alumniOf: {
    "@type": "EducationalOrganization",
    name: "Kyiv European University",
  },
  knowsAbout: [
    "Frontend Development",
    "JavaScript Frameworks",
    "Web Performance Optimization",
    "Technical SEO",
    "React Ecosystem",
    "TypeScript",
    "Web Accessibility",
    "SEO",
    "Frontend Architecture",
    "Code Optimization",
    "Technical Audits",
    "User Experience Design",
    "Agile Methodologies",
    "Cross-Functional Collaboration",
    "Mentorship",
    "Front-end Development",
    "Front dev",
    "Frontend dev",
    "CV",
    "Resume",
    "Project",
    "Projects",
    "Anton Belousov",
    "Anton",
    "Belousov",
    "Ukraine developer",
    "Ukraine developer",
    "React",
    "Next.js",
    "SEO",
    "Technical",
    "Apollo",
    "QraphQL",
    "TanStack",
    "Tailwind CSS",
    "Material UI",
    "Ant Design",
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Prettier",
    "Git",
    "GitHub",
    "GitLab",
    "Figma",
    "Postman",
    "Jest",
    "React Testing Library",
    "Lighthouse",
    "Google PageSpeed",
    "Schema.org",
    "WhatWG",
    "Microsoft Office",
    "LibreOffice",
    "Google Workspace",
    "Docs",
    "Expert"
  ],
  knowsLanguage: [
    {
      "@type": "Language",
      name: "English",
      proficiencyLevel: "Intermediate",
    },
    {
      "@type": "Language",
      name: "Ukrainian",
      proficiencyLevel: "Native",
    },
  ],
};