export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Anton Belousov",
  jobTitle: "Strong Middle Frontend Developer (React, Next.js, TypeScript)",
  email: "polpoltrop228@gmail.com",
  telephone: "+380663208556",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Kyiv",
    addressCountry: "Ukraine",
  },
  url: "https://github.com/AntonBelousovWEB",
  sameAs: [
    "https://github.com/AntonBelousovWEB",
    "https://www.linkedin.com/in/anton-belousov-1803042b1/",
    "/blog",
  ],
  description:
    "Frontend Developer with 5+ years building scalable React/Next.js apps. Performance (Core Web Vitals 90+), technical SEO, FSD architecture. 40-60% load time reduction, 30-50% PageSpeed improvements. Leads frontend teams.",
  hasOccupation: {
    "@type": "Occupation",
    name: "Frontend Developer",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Redux",
      "Redux Toolkit",
      "GraphQL",
      "REST API",
      "WebGL",
      "GLSL",
      "Service Worker",
      "Web Worker",
      "FSD",
      "Core Web Vitals",
      "Lighthouse",
      "PageSpeed Insights",
      "Technical SEO",
      "Schema.org",
      "Webpack",
      "Vite",
      "Git",
      "CI/CD",
      "GitHub Actions",
      "Vercel",
      "Jest",
      "React Testing Library",
    ],
    responsibilities:
      "Development of high-performance web applications, technical SEO optimization, code refactoring and performance improvements.",
  },
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Kyiv",
      addressCountry: "Ukraine",
    },
  },
  alumniOf: {
    "@type": "EducationalOrganization",
    name: "Kyiv European University",
  },
  knowsAbout: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Redux",
    "GraphQL",
    "REST API",
    "WebGL",
    "GLSL",
    "Service Worker",
    "Web Worker",
    "FSD",
    "Core Web Vitals",
    "Technical SEO",
    "System Design",
    "Frontend Architecture",
    "Code Refactoring",
    "Webpack",
    "Vite",
    "Git",
    "CI/CD",
    "Jest",
    "Anton Belousov",
    "Frontend Developer",
    "Ukraine",
  ],
  knowsLanguage: [
    {
      "@type": "Language",
      name: "English",
      proficiencyLevel: "B1/B2",
    },
    {
      "@type": "Language",
      name: "Ukrainian",
      proficiencyLevel: "Native",
    },
  ],
};